server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: BookingService
          uri: lb://BookingService
          predicates:
            - Path=/booking_service/**

        - id: PaymentService
          uri: lb://PaymentService
          predicates:
            - Path=/payment_service/**
    discovery:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost